### ISSUE TITLE
Suggestion: Expose `fromUser` parameter in Slider.valueChanges()

### ISSUE THREAD

**Issue by FlowMo7** [ReactiveCircus/FlowBinding#87]
I've encountered a use-case where I need to filter out the [`valueChanges()`](https://github.com/ReactiveCircus/FlowBinding/blob/master/flowbinding-material/src/main/java/reactivecircus/flowbinding/material/SliderValueChangeFlow.kt#L34) events from a Slider on whether the change has been initiated by a user-input or programmatically.
The [Slider.OnChangeListener](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/slider/Slider.java#L285) provides a boolean parameter `fromUser` for that indication.

I would see two possible approaches for such a functionality:

#### 1. Expose the `fromUser` boolean in the returned Flow
```kotlin
fun Slider.valueChangesWithFromUser(emitImmediately: Boolean = false): Flow<Pair<Float, Boolean>>
```
This would, however, introduce a second method for valuesChanged (as for the majority of uses, the fromUser parameter will not be necessary and will result in unnecessary packing / unpacking of the actual float variable), and the Pair as a return type may not be self describing.

#### 2. Introduce an optional parameter to tell the method which events to return
```kotlin
fun Slider.valueChangesWithFromUser(emitImmediately: Boolean = false, fromUser: Boolean? = null): Flow<Float>
```
This way, the method would encapsulate the filter logic, which I would have seen as:
* `fromUser = null`: all events are emitted
* `fromUser = false`: only events not initiated by a user input are emitted
* `fromUser = true`: only events initiated by a user input are emitted

Personally I would prefer the second solution, but I would love to hear your opinion on this, and if you like either approach and think this has a place in the library, I would be happy to create a PR for that.

**Comment by ychescale9** [comment]
How about a separate binding `SliderChangeEventFlow.kt`:

```kotlin
@CheckResult
@OptIn(ExperimentalCoroutinesApi::class)
fun Slider.changeEvents(emitImmediately: Boolean = false): Flow<SliderChangeEvent> = callbackFlow {
    checkMainThread()
    val listener = Slider.OnChangeListener { slider, value, fromUser ->
        safeOffer(
            SliderChangeEvent(
                slider = slider,
                value = value,
                fromUser = fromUser
            )
        )
    }
    addOnChangeListener(listener)
    awaitClose { removeOnChangeListener(listener) }
}
    .startWithCurrentValue(emitImmediately) {
        SliderChangeEvent(
            slider = this,
            value = value,
            fromUser = false
        )
    }
    .conflate()

class SliderChangeEvent(
    val slider: Slider,
    val value: Float,
    val fromUser: Boolean
)
```

And thanks for willing to contribute, you can take a look at `SeekBarChangeEventFlow.kt` and its docs and tests as a reference.

You'll also need to run `./gradlew apiDump` and check in the updated `xxx.api` file.

Let me know if you need anything else 😃

**Comment by FlowMo7** [comment]
Thanks for the code foe the separate binding and the hints for the development and test references.

Unfortunately, though, I just can't make the tests run in the project setup on my machine (running them results in e.g. a `Class not found: "reactivecircus.flowbinding.android.widget.SeekBarChangeEventFlowTest"` error), so I would only be able to add the tests blindfolded without every running them.

Therefore I seem to be unable to create a PR for this issue, I'm very sorry for that.

**Comment by ychescale9** [comment]
No need to feel sorry! Were you trying to run the test from IDE? This looks like an issue with Android Studio's run configuration. Removing all the Run/Debug configurations and doing an `Invalidate cache and restart` should fix this issue. Otherwise it should at least run from the command line `./gradlew flowbinding-android:connectedCheck`.

If you don't want to spend more time on this that's fine, just send the PR and I can take care of the tests 😃

**Comment by FlowMo7** [comment]
Thanks for the support!
Running the tests using the `connectedCheck` task worked for me, while invalidating the AndroidStudio cache unfortunately did not fix things in the IDE for me.

**Comment by ychescale9** [comment]
This is now available on Maven Central version `0.11.0`. Thanks again for the contribution!
